// <auto-generated />
using APIGUI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIGUI.Migrations
{
    [DbContext(typeof(Cosmic))]
    [Migration("20240326215627_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("APIGUI.ImageData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Copyright")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hdurl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CosmicImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "2019-04-12",
                            Explanation = "I ain't got time",
                            Hdurl = "https://apod.nasa.gov/apod/image/1904/JMD_Rosette_Rotated.jpg",
                            Title = "A Cosmic Rose: The Rosette Nebula in Monoceros"
                        },
                        new
                        {
                            Id = 2,
                            Date = "2019-08-13",
                            Explanation = "I ain't got time2",
                            Hdurl = "https://apod.nasa.gov/apod/image/1908/CannonSupernova_English_8404.jpg",
                            Title = "Supernova Cannon Expels Pulsar J0002"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
